<div id="brands-slider" class="owl-carousel owl-theme owl-loaded owl-drag">
    <div class="owl-stage-outer">
        <div class="owl-stage"
             style="transform: translate3d(-396px, 0px, 0px); transition: all 0.25s ease 0s; width: 2376px;">
            <?php foreach ($block->getBrandCollection() as $key=>$post){ ?>
            <div class="owl-item" style="width: 178px; margin-right: 20px;">
                <div class="item">
                    <img src="pub/media/brands/tmp/<?php echo $post->getLogo(); ?>" alt="<?php echo $post->getTitle(); ?>" />
                </div>
            </div>
            <?php } ?>
        </div>
    </div>
</div>

<script type="text/javascript">
    require(['jquery', 'jquery/ui'], function($){
        $(document).ready( function() {
            $('.owl-carousel').owlCarousel({
                loop:true,
                margin:10,
                responsiveClass:true,
                responsive:{
                    0:{
                        items:1,
                        nav:false,
                        autoplay:true,
                        autoplayTimeout: 1500,
                        dots: false
                    },
                    600:{
                        items:3,
                        nav:false,
                        autoplay:true,
                        autoplayTimeout: 1500,
                        dots: false
                    },
                    1000:{
                        items:4,
                        nav:false,
                        loop:true,
                        autoplay:true,
                        autoplayTimeout: 1500,
                        dots: false
                    }
                }
            });
        });
    });
</script>